services:
  - type: web
    name: student-admin-portal
    rootDir: .
    env: node
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DB_PATH
        value: /data/student_portal.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1