services:
  - type: web
    name: student-admin-portal
    rootDir: .
    env: node
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: DB_PATH
        value: /tmp/student_portal.db # free tier has no persistent disk; data resets on restarts
